# Generated by Django 4.2 on 2023-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_chovatel_cislo_prukazu_zvire_cislo_zvirete'),
    ]

    operations = [
        migrations.AddField(
            model_name='zvire',
            name='telefon',
            field=models.CharField(blank=True, help_text='Zadejte telefon v podobě: +420 777 777 777', max_length=16, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='chovatel',
            name='cislo_prukazu',
            field=models.CharField(error_messages={'blank': 'usí být vyplněno'}, help_text='Zadejte číslo průkazu', max_length=6, verbose_name='Prukaz'),
        ),
        migrations.AlterField(
            model_name='zvire',
            name='cislo_zvirete',
            field=models.CharField(error_messages={'blank': 'Musí být vyplněn'}, help_text='Zadejte cislo zvirete', max_length=100, verbose_name='Cislo zvirete'),
        ),
        migrations.AlterField(
            model_name='zvire',
            name='druh_zvirete',
            field=models.CharField(blank=True, choices=[('králík', 'Králík'), ('holub', 'holub'), ('drůbež', 'drůbež')], help_text='Vyberte druh zvířete', max_length=20, verbose_name='Druh'),
        ),
    ]
