# Generated by Django 4.2 on 2023-06-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_zvire_telefon_alter_chovatel_cislo_prukazu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zvire',
            name='telefon',
        ),
        migrations.AddField(
            model_name='zvire',
            name='plemeno',
            field=models.CharField(blank=True, help_text='Zadejte plemeno', max_length=80, verbose_name='plemeno'),
        ),
    ]
