# Generated by Django 4.2 on 2023-06-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_zvire_telefon_zvire_plemeno'),
    ]

    operations = [
        migrations.AddField(
            model_name='chovatel',
            name='fotografie',
            field=models.ImageField(blank=True, upload_to='chovatele', verbose_name='Fotografie'),
        ),
    ]
