# Generated by Django 4.2 on 2023-06-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_chovatel_fotografie'),
    ]

    operations = [
        migrations.AddField(
            model_name='chovatel',
            name='fotografie',
            field=models.ImageField(blank=True, upload_to='chovatel', verbose_name='Fotografie'),
        ),
    ]
