# Generated by Django 4.2 on 2023-06-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_chovatel_fotografie'),
    ]

    operations = [
        migrations.AddField(
            model_name='chovatel',
            name='foto',
            field=models.ImageField(blank=True, help_text='Zde můžete vložit fotografii vozu', null=True, upload_to='chovatel/', verbose_name='Fotka vozu'),
        ),
    ]
