# Generated by Django 4.2 on 2023-06-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_chovatel_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chovatel',
            name='foto',
        ),
        migrations.AddField(
            model_name='chovatel',
            name='fotografie',
            field=models.ImageField(blank=True, upload_to='chovatele', verbose_name='Fotografie'),
        ),
    ]
