# Generated by Django 4.2 on 2023-06-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_chovatel_fotografie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chovatel',
            name='fotografie',
        ),
    ]
