# Generated by Django 4.2 on 2023-06-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_chovatel_fotografie'),
    ]

    operations = [
        migrations.AddField(
            model_name='zvire',
            name='fotografie',
            field=models.ImageField(blank=True, null=True, upload_to='zvire', verbose_name='Fotografie'),
        ),
    ]
