# Generated by Django 4.2 on 2023-06-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_zvire_fotografie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zvire',
            name='fotografie',
        ),
    ]
