# Generated by Django 4.2 on 2023-06-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_chovatel_fotografie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chovatel',
            name='prijmeni',
            field=models.CharField(error_messages={'blank': 'Příjmení musí být vyplněno'}, help_text='Zadejte příjmení', max_length=50, verbose_name='Příjmení autora'),
        ),
    ]
